version: '3.7'
services:
  registry:
    image: registry:2.7.1
    ports:
     - "5000:5000"
    volumes:
     - /data/marcelo/docker/registry/data:/var/lib/registry
     - /home/marcelo/workspace/curso_docker/15_registry/03_Registry_with_login/auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_HOST: http://localhost:5000 







    